// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// run_kmeans_simple
Rcpp::List run_kmeans_simple(Rcpp::NumericMatrix x, int k, int seed);
RcppExport SEXP _KmeansReinitialization2021_run_kmeans_simple(SEXP xSEXP, SEXP kSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_kmeans_simple(x, k, seed));
    return rcpp_result_gen;
END_RCPP
}
// run_kmeans_centers
Rcpp::List run_kmeans_centers(Rcpp::NumericMatrix x, Rcpp::NumericMatrix centers);
RcppExport SEXP _KmeansReinitialization2021_run_kmeans_centers(SEXP xSEXP, SEXP centersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type centers(centersSEXP);
    rcpp_result_gen = Rcpp::wrap(run_kmeans_centers(x, centers));
    return rcpp_result_gen;
END_RCPP
}
// run_kmeans_reinit
Rcpp::List run_kmeans_reinit(Rcpp::NumericMatrix x, Rcpp::NumericMatrix centers, int seed);
RcppExport SEXP _KmeansReinitialization2021_run_kmeans_reinit(SEXP xSEXP, SEXP centersSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type centers(centersSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(run_kmeans_reinit(x, centers, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_KmeansReinitialization2021_run_kmeans_simple", (DL_FUNC) &_KmeansReinitialization2021_run_kmeans_simple, 3},
    {"_KmeansReinitialization2021_run_kmeans_centers", (DL_FUNC) &_KmeansReinitialization2021_run_kmeans_centers, 2},
    {"_KmeansReinitialization2021_run_kmeans_reinit", (DL_FUNC) &_KmeansReinitialization2021_run_kmeans_reinit, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_KmeansReinitialization2021(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
