# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_kmeans_simple <- function(x, k, seed) {
    .Call('_KmeansReinitialization2021_run_kmeans_simple', PACKAGE = 'KmeansReinitialization2021', x, k, seed)
}

run_kmeans_centers <- function(x, centers) {
    .Call('_KmeansReinitialization2021_run_kmeans_centers', PACKAGE = 'KmeansReinitialization2021', x, centers)
}

run_kmeans_reinit <- function(x, centers, seed) {
    .Call('_KmeansReinitialization2021_run_kmeans_reinit', PACKAGE = 'KmeansReinitialization2021', x, centers, seed)
}

